### ISSUE TITLE
10.50 support

### ISSUE THREAD

**Issue by W-i-n-7** [TheOfficialFloW/PPPwn#17]
nobody seems to be talking about this

**Comment by W-i-n-7** [comment]
i can test!

**Comment by rafaelflromao** [comment]
> nobody seems to be talking about this

Someone needs to get the functions offsets

**Comment by W-i-n-7** [comment]
> > nobody seems to be talking about this
> 
> Someone needs to get the functions offsets

i can try help with that
unfortunately i cant solder and i dont have any flashers/dumpers

if theres anything in software i can do then please tell me

**Comment by agentduckman12** [comment]
So does it work on 11.5

**Comment by fffoo** [comment]
> So does it work on 11.5

No moron, should not have updated
