### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by lompaket** [TheOfficialFloW/PPPwn#18]
I know it is something wrong with me cause everybody else can compile, but I get error

fatal error: sys/_lock.h: No such file or directory

I am on fedora. Help appreciated!

**Comment by MagmaSKV** [comment]
It happened to me and I think it was because I didn't do "sudo pip install -r requirements.txt"

**Comment by TheOfficialFloW** [comment]
git clone --recursive https://github.com/TheOfficialFloW/PPPwn

**Comment by W-i-n-7** [comment]
[PPPwn.zip](https://github.com/TheOfficialFloW/PPPwn/files/15178756/PPPwn.zip)
@lompaket 
precompiled
