### ISSUE TITLE
Se me apaga la play en el al iniciar el paso 2

### ISSUE THREAD

**Issue by Gggg10384928** [TheOfficialFloW/PPPwn#22]
Llevo todo el día intentando lo pero es que lo pongo todo bien y cuando llego al paso 2 se me apaga la play y al encenderla se pone a reconstruir el almacenamiento y después me toca volver a empezar a hacer todo de nuevo y llevo así todo el día, ¿alguien sabe la solución?
Si alguien sabe como solucionar este problema se lo agradezco.

**Comment by MagmaSKV** [comment]
En que version lo estas probando?

**Comment by Gggg10384928** [comment]
> ¿En qué versión lo estás probando?

En la versión 11.00

**Comment by Gggg10384928** [comment]
PORQUE CIERRAS EL PROBLEMAAAAAAA?????????🥲🥲🥲🥲🥲

**Comment by Gggg10384928** [comment]
En fin da igual,creo otro si eso

**Comment by nickcat325** [comment]
Your issue was closed likely because it's in spanish. Please restart your console 2 times. That's the solution.

Su problema probablemente se cerró porque está en español. Reinicie su consola 2 veces. Esa es la solución.
