### ISSUE TITLE
Sudo: pip not found

### ISSUE THREAD

**Issue by sharryboy88** [TheOfficialFloW/PPPwn#6]
I am trying so hard to get this requirement to get installed but all i get is this error above, what should i do???
the command i wanna use is: sudo pip install -r requirements.txt

**Comment by iMrDJAi** [comment]
sudo apt install python3

**Comment by jaideepv** [comment]
> I am trying so hard to get this requirement to get installed but all i get is this error above, what should i do???
> 
> the command i wanna use is: sudo pip install -r requirements.txt

You would need to run the command "sudo apt install python3-pip" to solve it
