### ISSUE TITLE
Does it work on 9.03

### ISSUE THREAD

**Issue by HiDeath98** [TheOfficialFloW/PPPwn#9]
First thing,
Thanks for releasing this, I'm really excited to test it out!

Does it work on 9.03 tho?
The description is really unclear, I'm afraid it's only related to 9.00 & 11.00,

Thanks once again,
Looking forward for your explanation!

**Comment by W-i-n-7** [comment]
by the looks of things people are working on porting it to all firmwares 9.00 through 11.00
but none is done **_yet_**
